[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_src_filter =
  +<*>
  -<diagnostics/>
lib_deps =
  knolleary/PubSubClient@^2.8
build_flags =
  -D EMS_SIMULATION=0
  -D CORE_DEBUG_LEVEL=1
  -Wall
  -Wextra
build_unflags =
  -std=gnu++11
build_src_flags =
  -std=gnu++17

[env:anenji_probe]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_src_filter =
  -<*>
  +<diagnostics/AnenjiProbe.cpp>
  +<drivers/AnenjiProtocol.cpp>
build_flags =
  -D CORE_DEBUG_LEVEL=1
  -Wall
  -Wextra
build_unflags =
  -std=gnu++11
build_src_flags =
  -std=gnu++17
